In [1]:
%%HTML
<iframe width="400" height="225"
src="https://www.youtube.com/embed/a8aDcLk4vRc?list=PLeo1K3hjS3uset9zIVzJWqplaWBiacTEU"
allowfullscreen></iframe>

# Single dimension array
A single dimensional array can be accessed much like a list

In [2]:
import numpy as np
a1 = np.array([5,6,9])
a1[0]

5

In [3]:
a1[1]

6

# Multiple dimension array
A multi-dimensional array must be defind with the appropriate extra square brackets

In [4]:
a2 = np.array([[1,2],[3,4],[5,6]])

# Array dimensionality
To see number of dimensions of an array, use .ndim command

In [5]:
a1.ndim 

1

In [6]:
a2.ndim

2

# Item size and data type
To show byte size of each element in the array. For this case the integers occupy 4 byes

In [7]:
a1.itemsize

4

In [8]:
a2.itemsize

4

In [9]:
a1.dtype 

dtype('int32')

In [10]:
a2.dtype

dtype('int32')

# Selecting the data type for an array
A datatype can be selected during initialization. Note how float64 takes up 8 bytes and initializes the values to floats

In [11]:
a3 = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)
a3.itemsize

8

In [12]:
a3

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

# Array size and shape
The size argument shows the number of elements in the whole array. The shape argument shows the M by N representation of the matrix

In [13]:
a1.size

3

In [14]:
a2.size

6

In [15]:
a3.size

6

In [16]:
a1.shape

(3,)

In [17]:
a3.shape

(3, 2)

# Complex number datatype
The complex number can also be represented as a dtype

In [18]:
a3 = np.array([[1,2],[3,4],[5,6]], dtype=complex)
a3

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

# Initializing to placeholder numbers
An array can be initialized to all zeros or ones, and must have a specified shape

In [19]:
a4 = np.zeros((3, 4))
a4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
a5 = np.ones((3, 4))
a5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Initializing a range inside of an array
Similar to the range function for a Python list, use arange. Like the native range function, the end index is non-inclusive. Additionally, the step argument can be used to initialize

In [21]:
a6 = np.arange(1,5)
a6

array([1, 2, 3, 4])

In [22]:
a7 = np.arange(1, 10, 2)
a7

array([1, 3, 5, 7, 9])

# Linspace function
Can specify a start number, end number, and the number of points to be generated. The generated numbers will be linearly spaced between the bounds

In [23]:
a8 = np.linspace(1, 5, 10)
a8

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
a9 = np.linspace(1, 5, 5)
a9

array([1., 2., 3., 4., 5.])

# Reshaping an array
Can reshape a 3,2 matrix to a 2,3 matrix. This is useful for matrix transposing. Note that this does not sort the array in place. Additionally, this can be used to vectorize a matrix

In [25]:
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
a2.shape

(3, 2)

In [27]:
a2_transpose = a2.reshape(2, 3)
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
a2_transpose

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
vec_a2 = a2.reshape(6, 1)
vec_a2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Flattening a matrix
The ravel function will flatten a matrix into a single dimension array. This does not affect the original array

In [30]:
a2_flat = a2.ravel()
a2_flat

array([1, 2, 3, 4, 5, 6])

# Mathematical function methods
Min, max function as expected. Sum will add all elements together

In [31]:
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
a2.min()

1

In [34]:
a2.max()

6

In [35]:
a2.sum()

21

# Matrix axes concept
Note that for array a2, axis 0 is vertical and axis 1 is horizontal. Thus the axes can be accessed for operations that act as follows

In [36]:
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
a2.sum(axis=0)

array([ 9, 12])

In [39]:
a2.sum(axis=1)

array([ 3,  7, 11])

# Square root
Square root is a general function of np, and can be used to take the square root of each function in an array

In [41]:
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
np.sqrt(a2)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

# Standard deviation
Standard deviation operates on the array as a whole and considers elements as a population

In [44]:
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
np.std(a2)

1.707825127659933

# Sample operations
Elementwise addition, multiplication, and division are possible. Most native operators are overloaded for element-wise computation

In [45]:
b = np.array([[1, 2], [3, 4]])
c = np.array([[5, 6], [7, 8]])

In [47]:
b

array([[1, 2],
       [3, 4]])

In [48]:
c

array([[5, 6],
       [7, 8]])

In [49]:
b + c

array([[ 6,  8],
       [10, 12]])

In [50]:
b / c

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [53]:
b ** c

array([[    1,    64],
       [ 2187, 65536]], dtype=int32)

In [56]:
c // b

array([[5, 3],
       [2, 2]], dtype=int32)

# Matrix multiplication
Use the dot method to take the product of two arrays

In [57]:
b

array([[1, 2],
       [3, 4]])

In [58]:
c

array([[5, 6],
       [7, 8]])

In [59]:
b.dot(c)

array([[19, 22],
       [43, 50]])