In [1]:
%%HTML
<iframe width="400" height="225"
src="https://www.youtube.com/embed/_d_Ka-ks2a0?list=PLeo1K3hjS3uset9zIVzJWqplaWBiacTEU" allowfullscreen></iframe>

# Python native indexing example
Note that the end bound is not inclusive. Adittionally, negative indexing can be used to access elements from the end

In [2]:
n = [6, 7, 8]
n[0:2]

[6, 7]

In [3]:
n[-1]

8

# Single dimension numpy slicing
Single dimension syntax is similar for list slicing in native Python

In [4]:
import numpy as np
a2 = np.array([6, 7, 8])
a2[0:2]

array([6, 7])

# Multi-dimensional array slicing
Index accessing uses 0-indexed row, column notation. When slicing multiple dimensions, the end index is not included. Additionally, the accessed elements may not be in the same shape as in the native array. Negative indexing is also allowed

In [5]:
a2 = np.array([[6, 7, 8], [1, 2, 3], [9, 3, 2]])
a2

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [6]:
a2[1, 2]

3

In [7]:
a2[0:2, 2]

array([8, 3])

In [8]:
a2[-1]  # Last row

array([9, 3, 2])

In [9]:
a2[-1, 0:2]  # Last row, columns 0 and 1

array([9, 3])

# Accessing all elements in a row/column
Use the colon operator to access all elements. Note how the shape may or may not be preserved based on how many elements are being accessed

In [10]:
a2

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [11]:
a2[:, 2]

array([8, 3, 2])

In [12]:
a2[:, 1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

# Iterating through an array
Python native syntax can be used to iterating over rows or columns. An array can be flattened using the flat method to access each element in the array

In [13]:
a2

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [14]:
for row in a2:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [15]:
for cell in a2.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


# Stacking two arrays together
The vstack command can be used for vertical concatenation, and takes a tuple as an argument. Likewise, the hstack command is used horizontally

In [16]:
a3 = np.arange(6).reshape(3, 2)  # Numbers 0-5 in a 3x2 matrix
a4 = np.arange(6, 12).reshape(3, 2)

In [17]:
a3

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
a4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
np.vstack((a3, a4))  # Argument is a tuple

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
np.hstack((a3, a4))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

# Splitting an array
The hsplit command can be used to split arrays. This returns a list. Likewise a vertical split can be used

In [21]:
a5 = np.arange(30).reshape(2, 15)
a5

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [23]:
result = np.hsplit(a5, 3)  # Result is a list
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [24]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [25]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [26]:
result2 = np.vsplit(a5, 2)
result2[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [28]:
result2[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Boolean array indexing
A numpy array can be created which represents the indices of another array that meet a boolean condition. A boolean array can be used to extract only values with True indices from the original array

In [30]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [33]:
a[b]  # The values greater than 4

array([ 5,  6,  7,  8,  9, 10, 11])

# Reassigning values based on boolean indexing
Values meeting a boolean condition can be operated on exclusively

In [35]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])