In [1]:
%%HTML
<iframe width="400" height="225"
src="https://www.youtube.com/embed/XawR6CjAYV4?list=PLeo1K3hjS3uset9zIVzJWqplaWBiacTEU" allowfullscreen></iframe>

Additional documentation at
https://docs.scipy.org/doc/numpy/reference/generated/numpy.nditer.html
https://docs.scipy.org/doc/numpy/reference/ufuncs.html#broadcasting

In [2]:
import numpy as np

In [3]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

# Iterating via for loop
A basic for loop can be used to iterate over rows. Additionally, a nested loop can be used to access individual elements. The flatten function is similar to the nested loop

In [4]:
for row in a:
    print(row)

[0 1 2]
[3 4 5]


In [5]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5


In [6]:
for cell in a.flatten():
    print(cell)
    

0
1
2
3
4
5


#  Basic np.nditer operations
The np.nditer function takes an array and constructs an iterator based on the specified iteration type. The 'C' (for C copmuter language) order is similar to flatten and prints by row then by column. However, to print by column then by row, Fortran order, use 'F'

In [7]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5


In [9]:
for x in np.nditer(a, order='F'):
    print(x)

0
3
1
4
2
5


# Using flags in np.nditer
The external_loop flag can be used to separate values into groups. The readwrite optional flag can be used to modify the original array in place

In [11]:
for x in np.nditer(a, order='F', flags=['external_loop']):
    print(x)

[0 3]
[1 4]
[2 5]


In [12]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x
a

array([[ 0,  1,  4],
       [ 9, 16, 25]])

# Iterating through 2 arrays at the same time
Python native unpacking syntax can be used to iterate on mulitiple arrays even with different dimensions. Note how the elements in array b are repeated when printing. See https://docs.scipy.org/doc/numpy/reference/ufuncs.html#broadcasting for explanation of compatible dimensions

In [14]:
b = np.arange(3, 15, 4).reshape(3, 1)
b

array([[ 3],
       [ 7],
       [11]])

In [18]:
a = a.reshape(3, 2)
a

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

In [19]:
for x, y in np.nditer([a, b]):
    print(x, y)

0 3
1 3
4 7
9 7
16 11
25 11
